[package]
version = "0.1.0"
name = "lwe-lr-program"
edition = "2021"

[dependencies]
simple_lwe = {path = "/home/gkigiermo/ZK/simple-lwe"}
alloy-sol-types = { workspace = true }
sp1-zkvm = "1.1.0"
lwe-lr-lib = { path = "../lib" }